# Generated by Django 4.2.2 on 2023-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing_active_listing_buyer_listing_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='numBids',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
